apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: go-app
  version: v1.0.0

images:
  - name: go-app
    newTag: latest 