apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: default
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 