name: Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/go-argo-cd:latest
          ${{ secrets.DOCKER_USERNAME }}/go-argo-cd:${{ github.sha }}

    - name: Update deployment
      run: |
        # Update image in deployment.yaml
        sed -i "s|image: go-app:latest|image: ${{ secrets.DOCKER_USERNAME }}/go-argo-cd:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Commit and push
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "Deploy ${{ github.sha }}" || exit 0
        git push 